name: Run Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build
        run: |
          cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release 
          cmake --build build
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
